[package]
name = "skia-safe"

description = "Safe Skia Bindings for Rust"
homepage = "https://github.com/rust-skia/rust-skia"
repository = "https://github.com/rust-skia/rust-skia"
documentation = "https://rust-skia.github.io/doc/skia_safe"
readme = "README.md"
# 5 max
keywords = ["skia", "rust-bindings", "vulkan", "opengl", "pdf"]
# 6 max
categories = ["api-bindings", "graphics", "multimedia::images", "rendering::graphics-api", "visualization"] 
license = "MIT"

version = "0.40.1"
authors = ["Armin Sander <armin@replicator.org>"]
edition = "2018"

[lib]
doctest = false

[features]
default = ["binary-cache"]
gl = ["gpu", "skia-bindings/gl"]
egl = ["gl", "skia-bindings/egl"]
x11 = ["gl", "skia-bindings/x11"]
wayland = ["egl", "skia-bindings/wayland"]
vulkan = ["gpu", "skia-bindings/vulkan"]
metal = ["gpu", "skia-bindings/metal"]
d3d = ["gpu", "winapi", "wio", "skia-bindings/d3d"]
textlayout = ["skia-bindings/textlayout"]
webp = ["webp-encode", "webp-decode"]
webp-encode = ["skia-bindings/webp-encode"]
webp-decode = ["skia-bindings/webp-decode"]
use-system-jpeg-turbo = ["skia-bindings/use-system-jpeg-turbo"]
binary-cache = ["skia-bindings/binary-cache"]

# implied only, do not use
gpu = []
# deprecated since 0.25.0, forwarded to skia-bindings with the intent to show warnings while build.rs is running
svg = ["skia-bindings/svg"]
shaper = ["textlayout", "skia-bindings/shaper"]

[dependencies]
bitflags = "1.2"
lazy_static = "1.4"
skia-bindings = { version = "=0.40.1", path = "../skia-bindings", default-features = false }
# for d3d types
winapi = { version = "0.3.9", features = ["d3d12", "dxgi"], optional = true }
# for ComPtr
wio = { version = "0.2.2", optional = true }

[dev-dependencies]
serial_test = "0.5"
static_assertions = "1.1"

# gl-window
[target.'cfg(not(target_os = "android"))'.dev-dependencies]
glutin = "0.27"
gl-rs = { package = "gl", version = "0.14.0" }

