[package]

name = "skia-bindings"
description = "Skia Bindings for Rust"
homepage = "https://github.com/rust-skia/rust-skia/skia-bindings"
repository = "https://github.com/rust-skia/rust-skia"
readme = "README.md"
keywords = ["skia", "rust-bindings", "vulkan", "opengl", "pdf"]
categories = ["external-ffi-bindings", "graphics", "multimedia::images", "rendering::graphics-api", "visualization"]
license = "MIT"

version = "0.40.1"
authors = ["LongYinan <lynweklm@gmail.com>", "Armin Sander <armin@replicator.org>"]
edition = "2018"
build = "build.rs"
links = "skia"
include = [ 
	"Cargo.toml", 
	"build.rs", 
	"build_support.rs", 
	"build_support/**/*.rs", 
	"src/**/*.h", 
	"src/**/*.cpp", 
	"src/defaults.rs", 
	"src/icu.rs", 
	"src/impls.rs",
	"src/lib.rs" ]

[lib]
doctest = false

# Metadata used from inside the packaged crate that defines where to download skia and depot_tools archives from.
# Note: use short hashes here because of filesystem path size restrictions.
[package.metadata]
skia = "m91-0.39.3"
depot_tools = "a110bf6"

[features]
default = ["binary-cache"]
gl = []
egl = []
wayland = []
x11 = []
vulkan = []
metal = []
d3d = []
textlayout = []
webp = ["webp-encode", "webp-decode"]
webp-encode = []
webp-decode = []
# sys libraries
use-system-jpeg-turbo = ["mozjpeg-sys"]
# deprecated since 0.25.0
svg = []
shaper = ["textlayout"]
binary-cache = ["ureq", "flate2", "tar"]

[dependencies]

mozjpeg-sys = { version = "0", features=["with_simd"], optional=true }

[build-dependencies]
cc = "1.0.37"
bindgen = "0.58.1"

# For enum variant name replacements.

regex = "1.4.5"
heck = "0.3.1"

# for downloading and extracting prebuilt binaries and skia / depot_tools archives:
ureq = { version = "2.0.1", optional = true }
flate2 = { version = "1.0.7", optional = true }
tar = { version = "0.4.26", optional = true }

# On the CI we don't specify the libclang location explicitly and PATH contains
# multiple of them. clang-sys version 1.0.2 changed the resolvement order.
# https://github.com/KyleMayes/clang-sys/pull/118
clang-sys = "=1.0.2"

# for reading .cargo.vcs_info.json to get the repository sha1 that is used to download
# the matching prebuilt binaries.
serde_json = "1.0.39"
# for reading Cargo.toml from within a package.
toml = "0.5.1"
